config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "flats#index"
  get "/flats/:id", to: "flats#show", as: :flat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  before_action :set_flats

  def index
  end

  def show
    @flat = @flats.find {|flat| flat["id"] == params[:id].to_i}
  end

  private

  def set_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(URI.open(url).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <h1>Flats</h1>
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-4 mb-4">
      <div class="card h-100">
        <img src="<%= flat["imageUrl"] %>" class="card-img-top" alt="">
        <div class="card-body">
          <h5 class="card-title"><%= flat["name"] %></h5>
          <p class="card-text"><%= flat["price"] %> €</p>
          <%= link_to "Visit flat", flat_path(flat["id"]), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container py-4">
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h1><%= @flat["name"] %></h1>
        <span class="badge bg-secondary"><%= @flat["price"] %> €</span>
      </div>
      <img class="w-100 rounded" src="<%= @flat["imageUrl"] %>" alt="">
      <%= link_to "Back to flats", root_path, class: "btn btn-primary mt-4"  %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LivecodeFlats1530</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>